using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class AudioModel
{
    [RealtimeProperty(6, true, true)]
    private int _audClp;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class AudioModel : IModel {
    // Properties
    public int audClp {
        get { return _cache.LookForValueInCache(_audClp, entry => entry.audClpSet, entry => entry.audClp); }
        set { if (value == audClp) return; _cache.UpdateLocalCache(entry => { entry.audClpSet = true; entry.audClp = value; return entry; }); FireAudClpDidChange(value); }
    }
    
    // Events
    public delegate void AudClpDidChange(AudioModel model, int value);
    public event         AudClpDidChange audClpDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool audClpSet;
        public int  audClp;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public AudioModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireAudClpDidChange(int value) {
        try {
            if (audClpDidChange != null)
                audClpDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        AudClp = 6,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _audClp = audClp;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteVarint32Length((uint)PropertyID.AudClp, (uint)_audClp);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.audClpSet)
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.AudClp, (uint)entry.audClp);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteVarint32((uint)PropertyID.AudClp, (uint)_audClp);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.audClpSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.audClpSet)
                    stream.WriteVarint32((uint)PropertyID.AudClp, (uint)entry.audClp);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool audClpExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.audClpSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.AudClp: {
                    int previousValue = _audClp;
                    
                    _audClp = (int)stream.ReadVarint32();
                    
                    if (!audClpExistsInChangeCache && _audClp != previousValue)
                        FireAudClpDidChange(_audClp);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
