using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;
[RealtimeModel]
public partial class ModelAudio
{
   [ RealtimeProperty(1, true, true)]
    private int _clipID;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class ModelAudio : IModel {
    // Properties
    public int clipID {
        get { return _cache.LookForValueInCache(_clipID, entry => entry.clipIDSet, entry => entry.clipID); }
        set { if (value == clipID) return; _cache.UpdateLocalCache(entry => { entry.clipIDSet = true; entry.clipID = value; return entry; }); FireClipIDDidChange(value); }
    }
    
    // Events
    public delegate void ClipIDDidChange(ModelAudio model, int value);
    public event         ClipIDDidChange clipIDDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool clipIDSet;
        public int  clipID;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public ModelAudio() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireClipIDDidChange(int value) {
        try {
            if (clipIDDidChange != null)
                clipIDDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        ClipID = 1,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _clipID = clipID;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteVarint32Length((uint)PropertyID.ClipID, (uint)_clipID);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.clipIDSet)
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.ClipID, (uint)entry.clipID);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteVarint32((uint)PropertyID.ClipID, (uint)_clipID);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.clipIDSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.clipIDSet)
                    stream.WriteVarint32((uint)PropertyID.ClipID, (uint)entry.clipID);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool clipIDExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.clipIDSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.ClipID: {
                    int previousValue = _clipID;
                    
                    _clipID = (int)stream.ReadVarint32();
                    
                    if (!clipIDExistsInChangeCache && _clipID != previousValue)
                        FireClipIDDidChange(_clipID);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
