using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class TeamModel
{
    [RealtimeProperty(20, true, true)]
    private int _team;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class TeamModel : IModel {
    // Properties
    public int team {
        get { return _cache.LookForValueInCache(_team, entry => entry.teamSet, entry => entry.team); }
        set { if (value == team) return; _cache.UpdateLocalCache(entry => { entry.teamSet = true; entry.team = value; return entry; }); FireTeamDidChange(value); }
    }
    
    // Events
    public delegate void TeamDidChange(TeamModel model, int value);
    public event         TeamDidChange teamDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool teamSet;
        public int  team;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public TeamModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireTeamDidChange(int value) {
        try {
            if (teamDidChange != null)
                teamDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        Team = 20,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _team = team;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteVarint32Length((uint)PropertyID.Team, (uint)_team);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.teamSet)
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.Team, (uint)entry.team);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteVarint32((uint)PropertyID.Team, (uint)_team);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.teamSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.teamSet)
                    stream.WriteVarint32((uint)PropertyID.Team, (uint)entry.team);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool teamExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.teamSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.Team: {
                    int previousValue = _team;
                    
                    _team = (int)stream.ReadVarint32();
                    
                    if (!teamExistsInChangeCache && _team != previousValue)
                        FireTeamDidChange(_team);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
