using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class Tm
{
    [RealtimeProperty(15, true, true)]
    private int _t;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class Tm : IModel {
    // Properties
    public int t {
        get { return _cache.LookForValueInCache(_t, entry => entry.tSet, entry => entry.t); }
        set { if (value == t) return; _cache.UpdateLocalCache(entry => { entry.tSet = true; entry.t = value; return entry; }); FireTDidChange(value); }
    }
    
    // Events
    public delegate void TDidChange(Tm model, int value);
    public event         TDidChange tDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool tSet;
        public int  t;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public Tm() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireTDidChange(int value) {
        try {
            if (tDidChange != null)
                tDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        T = 15,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _t = t;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteVarint32Length((uint)PropertyID.T, (uint)_t);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.tSet)
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.T, (uint)entry.t);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteVarint32((uint)PropertyID.T, (uint)_t);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.tSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.tSet)
                    stream.WriteVarint32((uint)PropertyID.T, (uint)entry.t);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool tExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.tSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.T: {
                    int previousValue = _t;
                    
                    _t = (int)stream.ReadVarint32();
                    
                    if (!tExistsInChangeCache && _t != previousValue)
                        FireTDidChange(_t);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
